title: Ancient & New
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.3900607
  brandStrength: 0.01702128
  rhythmicContrast: 0.9702128
  brandColors:
    - '#FEFEFE'
    - '#292929'
    - '#646161'
    - '#908E8D'
    - '#B4B2B2'
  lightness: 0.6493858
typography_spectrum: 0.7914894
description: and inbetween
navigation:
  - name: facebook page
    url: 'https://m,facebook.com/irish-bog-art177229418973864/'
    type: external
layout_spectrum: 0.3348164057824761
name: Irish Bog Oak & Art
